# Generated by Django 5.2.17 on 2026-10-06 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0016_customlist_tiers_customlistitem_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='customlist',
            name='completed_placement',
            field=models.CharField(choices=[('normal', 'Normal'), ('bottom', 'At bottom')], default='normal', help_text='Where completed items appear in list order.', max_length=10),
        ),
        migrations.AddField(
            model_name='customlist',
            name='default_layout',
            field=models.CharField(blank=True, choices=[('grid', 'Grid'), ('table', 'Table'), ('tiers', 'Tiers')], default='', help_text='Default layout for this list.', max_length=20),
        ),
        migrations.AddField(
            model_name='customlist',
            name='default_sort',
            field=models.CharField(blank=True, choices=[('date_added', 'Date Added'), ('custom', 'Custom'), ('title', 'Title'), ('media_type', 'Media Type'), ('rating', 'Rating'), ('progress', 'Progress'), ('status', 'Status'), ('release_date', 'Release Date'), ('start_date', 'Start Date'), ('end_date', 'End Date'), ('platform', 'Platform'), ('tier', 'Tier')], default='', help_text='Default sort order for this list.', max_length=20),
        ),
        migrations.AddField(
            model_name='customlist',
            name='default_sort_direction',
            field=models.CharField(blank=True, choices=[('asc', 'Ascending'), ('desc', 'Descending')], default='', help_text='Default sort direction for this list.', max_length=4),
        ),
        migrations.AddField(
            model_name='customlist',
            name='status_tab',
            field=models.CharField(choices=[('all', 'All'), ('in_progress', 'In Progress'), ('planning', 'Plan to Watch'), ('completed', 'Completed'), ('paused', 'On-Hold'), ('dropped', 'Dropped')], default='all', help_text='Default status tab for this list.', max_length=20),
        ),
    ]
